### PR TITLE
tracker: support session config for tracker

### LINKED ISSUE #825: session config support for internal TiDB in schema tracker
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   set `sql_mode` `NO_ZERO_DATE,NO_ZERO_IN_DATE` for the downstream TiDB and running a DM task for a table with `default"0000-00-00 00:00:00"`.

2. What did you expect to see?

    no errors got.

3. What did you see instead?

    
image

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.0-beta.1 but for all version until this issue reported
        ```

---

we have introduced `session` for `DBConfig`, we may use `sql_mode` in `session` for TiDB with mockTiKV in schema tracker.

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
close #825 

### What is changed and how it works?
- set SetSystemVar when create tracker

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

File: pkg/schema/tracker_test.go [hunk 1]
```diff
@@ -34,10 +34,51 @@ var _ = Suite(&trackerSuite{})
...
 type trackerSuite struct{}
 
+func (s *trackerSuite) TestSessionCfg(c *C) {
+	log.SetLevel(zapcore.ErrorLevel)
+
+	sessionCfg := map[string]string{"sql_mode": "HaHa"}
+	tracker, err := schema.NewTracker(sessionCfg)
+	c.Assert(err, NotNil)
+
+	tracker, err = schema.NewTracker(nil)
```
Comment (lance6716) [inline pkg/schema/tracker_test.go:44]: check `err` or use `_`?

File: pkg/schema/tracker_test.go [hunk 2]
```diff
@@ -34,10 +34,51 @@ var _ = Suite(&trackerSuite{})
...
+	sessionCfg = map[string]string{"sql_mode": "NO_ZERO_DATE,NO_ZERO_IN_DATE,ANSI_QUOTES"}
+	tracker, err = schema.NewTracker(sessionCfg)
+	c.Assert(err, IsNil)
+
+	err = tracker.Exec(ctx, "", "create database testdb;")
+	c.Assert(err, IsNil)
+
+	// Now create the table with ANSI_QUOTES and ZERO_DATE
+	err = tracker.Exec(ctx, "testdb", "create table \"foo\" (a varchar(255) primary key, b DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00')")
+	c.Assert(err, IsNil)
```
Comment (lance6716) [inline pkg/schema/tracker_test.go:63]: should it return error because `b` is ZERO_DATE and SQL mode is `NO_ZERO_DATE`?

update: seems `STRICT_TRANS_TABLES` should also be set, to prevent using ZERO_DATE value. 

https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date

**Comment by GMHDBJD** [comment]
@lance6716 fix wrong commit in 6cd352a. PTAL again

**Comment by lance6716** [comment]
/run-all-tests

LGTM
