### PR TITLE
task_checker: don't auto-resume for wrong datetime value

### LINKED ISSUE #921: do not auto resume for "Error 1366" error
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

   `Incorrect datetime value: '466261494-02-09 03:09:21' for column 'c2' at row 1"`

    `[2020/08/24 15:33:20.353 +08:00] [INFO] [task_checker.go:350] ["dispatch auto resume task"] [component="task checker"] [task=task_single]`

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.0-rc
        ```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
fix #921

### What is changed and how it works?
add this type of error to `UnsupportedDMLMsgs` (can't verify this is the right place)

### Check List 

Tests 

 - hard to find a MariaDB 10.0, can't imitate using newer MariaDB and mysql56_temporal_format = OFF

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

File: pkg/retry/errors.go [hunk 1]
```diff
@@ -37,6 +37,7 @@ var (
 	UnsupportedDMLMsgs = []string{
 		"Error 1062: Duplicate entry",
 		"Error 1406: Data too long for column",
+		"Error 1366: Incorrect datetime value",
```
Comment (csuzhangxc) [inline pkg/retry/errors.go:40]: How about handing other `Error 1366` too? maybe you can search TiDB repo (`tidb/errno/errcode.go`) to got the meaning of this code.

Comment (lance6716) [reply pkg/retry/errors.go:40]: I guess it's no help keep retrying

https://github.com/pingcap/tidb/blob/0fd81a83e8a0f0c799e006b0be03205533ca2750/executor/insert_common.go#L287

seems in fact most errors could not resolved by retry 🤔

Comment (csuzhangxc) [reply pkg/retry/errors.go:40]: > seems in fact most errors could not resolved by retry 

YES, but we don't know which errors could be resolved by retry, 😢

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM
