### PR TITLE
worker: sync master's endpoint peroidcally

### LINKED ISSUE #1110: worker offline after kill master
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
start multiple masters
join worker with one master
kill that master
run `list-member --worker`
2. What did you expect to see?
worker online
3. What did you see instead?
```
"workers": [
                    {
                        "name": "worker2",
                        "addr": "127.0.0.1:8263",
                        "stage": "offline",
                        "source": ""
                    }
                ]
```
4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        master
        ```
5 root cause
worker [keepalive](https://github.com/pingcap/dm/blob/aef0f37df67a7a49d49fed1bb555042606c80436/dm/worker/join.go#L98) with join url only

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #1110, part of #1127

### What is changed and how it works?
use `MemberList` and `GetClientURLs` to get all master's endpoint

### Check List 

Tests 

 - Integration test
 - Manual test
  check DEBUG message in log

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Comment by lance6716** [comment]
BTW, what's the recommended version upgrade action, need modify test case. join new master and kill old?

File: dm/worker/server.go [hunk 1]
```diff
@@ -177,6 +184,28 @@ func (s *Server) Start() error {
...
+		clientURLs = clientURLs[:0]
+		resp, err := s.etcdClient.MemberList(ctx)
+		if err != nil {
+			log.L().Error("can't get etcd member list", zap.Error(err))
+		} else {
+			for _, m := range resp.Members {
+				clientURLs = append(clientURLs, m.GetClientURLs()...)
+			}
+			log.L().Debug("will sync endpoints to", zap.Strings("client URLs", clientURLs))
+			s.etcdClient.SetEndpoints(clientURLs...)
```
Comment (csuzhangxc) [inline dm/worker/server.go:199]: How about only `SetEndpoints` if `clientURLs` exactly changed?

File: dm/worker/server.go [hunk 2]
```diff
@@ -48,6 +48,7 @@ var (
 	keepaliveTimeout        = 3 * time.Second
 	keepaliveTime           = 3 * time.Second
 	retryConnectSleepTime   = time.Second
+	syncMasterEndpointsTime = 3 * time.Second // enough?
```
Comment (csuzhangxc) [inline dm/worker/server.go:51]: no better idea yet

**Review by csuzhangxc — COMMENTED** [review]
rest LGTM

File: dm/worker/server.go (hunk 1 above)
Comment (lance6716) [reply dm/worker/server.go]: https://github.com/pingcap/dm/pull/1139/commits/dab32014cac6d3655df20ab32341ecc5e18cf45a

File: dm/worker/server.go [hunk 3]
```diff
@@ -177,6 +184,41 @@ func (s *Server) Start() error {
...
+		}
+
+		for _, m := range resp.Members {
+			clientURLs = append(clientURLs, m.GetClientURLs()...)
+		}
+		if utils.NonRepeatStringsEqual(clientURLs, lastClientUrls) {
+			log.L().Debug("etcd member list doesn't change", zap.Strings("client URLs", clientURLs))
+			return
+		}
+		log.L().Debug("will sync endpoints to", zap.Strings("client URLs", clientURLs))
```
Comment (csuzhangxc) [inline dm/worker/server.go:206]:
```suggestion
		log.L().Info("will sync endpoints to", zap.Strings("client URLs", clientURLs))
```

?

File: dm/worker/server.go [hunk 4]
```diff
@@ -177,6 +184,41 @@ func (s *Server) Start() error {
...
+		s.etcdClient.SetEndpoints(clientURLs...)
+		lastClientUrls = clientURLs
```
Comment (csuzhangxc) [inline dm/worker/server.go:208]: if we modify `clientURLs` later, then `lastClientUrls` may be modified to the same content too. https://play.golang.org/p/sPmSP63gv6F

File: dm/worker/server.go [hunk 5]
```diff
@@ -177,6 +184,42 @@ func (s *Server) Start() error {
...
+		if err != nil {
+			log.L().Error("can't get etcd member list", zap.Error(err))
+			return
+		}
+
+		for _, m := range resp.Members {
+			clientURLs = append(clientURLs, m.GetClientURLs()...)
+		}
+		if utils.NonRepeatStringsEqual(clientURLs, lastClientUrls) {
+			log.L().Info("etcd member list doesn't change", zap.Strings("client URLs", clientURLs))
```
Comment (csuzhangxc) [inline dm/worker/server.go:203]:
```suggestion
			log.L().Debug("etcd member list doesn't change", zap.Strings("client URLs", clientURLs))
```

this can still be `Debug`?

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Review by lichunzhu — APPROVED** [review]
LGTM
