### PR TITLE
syncer: remove auto_random when track table from downstream

### LINKED ISSUE #1715: [ddl:8216]Invalid auto random: column uuid is not the integer primary key, or the primary key is nonclustered
dm version: v2.0.3
tiup & tiup-dm: v1.4.3

Table structure and data have been desensitized

This is a requirement for multiple data sources to merge tables

mysql：
⁣CREATE TABLE `a_1` (
  `id` bigint(20) NOT NULL,
  `uid` bigint(20) NOT NULL,
  `a` tinyint(1) NOT NULL DEFAULT '0',
  `b` tinyint(1) NOT NULL DEFAULT '0',
  `c` int(11) NOT NULL,
  `d` text COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
⁣⁣
⁣
tidb：
⁣CREATE TABLE `a` (
  `uuid` bigint(20) NOT NULL AUTO_RANDOM,
  `id` bigint(20) NOT NULL,
  `uid` bigint(20) NOT NULL,
  `a` tinyint(1) NOT NULL DEFAULT '0',
  `b` tinyint(1) NOT NULL DEFAULT '0',
  `c` int(11) NOT NULL,
  `d` text COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`uuid`)
  KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

query-status info：
query-status asd
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "",
            "sourceStatus": {
                "source": "cnf",
                "worker": "xxxx",
                "result": null,
                "relayStatus": null
            },
            "subTaskStatus": [
                {
                    "name": "testtask",
                    "stage": "Paused",
                    "unit": "Sync",
                    "result": {
                        "isCanceled": false,
                        "errors": [
                            {
                                "ErrCode": 44003,
                                **"ErrClass": "schema-tracker",**
                                "ErrScope": "downstream",
                                "ErrLevel": "high",
                                **"Message": "startLocation: [position: (, 0), gtid-set: ], endLocation: [position: (mysql-bin.0073, 858627), gtid-set: 3580cb9-11e7-b133-525400bc861-125176714,3e8ecf-3b9-11e7-b133-5254005d54:1-135811]: failed to create table for `test`.`a_1` in schema tracker",
                                "RawCause": "[ddl:8216]Invalid auto random: column uuid is not the integer primary key, or the primary key is nonclustered",**
                                "Workaround": ""
                            }
                        ],
                        "detail": null
                    },
                    "unresolvedDDLLockID": "",
                    "sync": {
                        "totalEvents": "0",
                        "totalTps": "0",
                        "recentTps": "0",
                        "masterBinlog": "(mysql-bin.004, 694)",
                        "masterBinlogGtid": "35b18-3eb-11e7-b13-6:1-1252063311e2ecf-3e11e7-b133-0095d541-170535811",
                        "syncerBinlog": "(mysql-bin.0013, 85284)",
                        "syncerBinlogGtid": "3580cb18-3eb9-17-b133-52540bc986:1-1517714,3ecf-3eb11e7-b1-524d54:1-0535811",
                        "blockingDDLs": [
                        ],
                        "unresolvedGroups": [
                        ],
                        "synced": false,
                        "binlogType": "remote"
                    }
                }
            ]
        },

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #1715 

### What is changed and how it works?
as title

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

File: syncer/syncer.go [hunk 1]
```diff
@@ -684,6 +684,19 @@ func (s *Syncer) trackTableInfoFromDownstream(tctx *tcontext.Context, origSchema
 		createStmt.Table.Schema = model.NewCIStr(origSchema)
 		createStmt.Table.Name = model.NewCIStr(origTable)
 
+		// schema tracker sets non-clustered index, so can't handle auto_random.
```
Comment (Ehco1996) [inline syncer/syncer.go:687]: Although we have turned `tidb_enable_clustered_index` off in `defaultGlobalVars`, the user can turn it back on via the configuration file, is there a problem if we hard delete the `ColumnOptionAutoRandom` there?

File: syncer/syncer.go [hunk 2]
```diff
@@ -684,6 +684,19 @@ func (s *Syncer) trackTableInfoFromDownstream(tctx *tcontext.Context, origSchema
...
+		for _, col := range createStmt.Cols {
+			for i, opt := range col.Options {
+				if opt.Tp == ast.ColumnOptionAutoRandom {
+					newOpt := make([]*ast.ColumnOption, 0, len(col.Options)-1)
+					newOpt = append(newOpt, col.Options[0:i]...)
+					newOpt = append(newOpt, col.Options[i+1:len(col.Options)]...)
```
Comment (Ehco1996) [inline syncer/syncer.go:693]: Can we just remove "ColumnOptionAutoRandom" from "col.Option" instead of creating a new opt array?

**Review by Ehco1996 — COMMENTED** [review]
rest LGTM

File: syncer/syncer.go (hunk 1 above)
Comment (lance6716) [reply syncer/syncer.go:687]: the schema tracker is mainly used to 

1. get column names because they are not written in binlog row events.
2. calculate if two row changing an be sent concurrently by PK/UK
3. calculate information of optimistic shard DDL

(don't know if I forget something, cc @GMHDBJD )

I think there's no harm to delete `ColumnOptionAutoRandom`, but agree we'd better reduce the modification. Will fix later

File: syncer/syncer.go (hunk 2 above)
Comment (lance6716) [reply syncer/syncer.go]: https://github.com/pingcap/dm/pull/1823/commits/3243b0abe83146921974f6eedf2dc5462be7b830

**Comment by GMHDBJD** [comment]
Maybe we can add integration test for `auto_random` like `auto_increment` in [downstream_more_column](https://github.com/pingcap/dm/blob/master/tests/downstream_more_column/run.sh)

**Comment by lance6716** [comment]
> Maybe we can add integration test for `auto_random` like `auto_increment` in [downstream_more_column](https://github.com/pingcap/dm/blob/master/tests/downstream_more_column/run.sh)

now the downstream in CI is TiDB v5, so SHOW CREATE TABLE will attach CLUSTERED INDEX column comment, which will not trigger this problem.

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by Ehco1996** [comment]
@lance6716 need fix conflicts
