### PR TITLE
fix(load): stop goroutines after restore returned

### LINKED ISSUE #743: the stage of load unit is still running after encountered "Error 1067: Invalid default value for 'ct'"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    0. set `NO_ZERO_DATE` `sql_mode` for the downstream TiDB.
    1. create a table with `DEFAULT '0000-00-00 00:00:00'`
        ```sql
        CREATE TABLE `tbl` (
          `c1` int(11) NOT NULL,
          `ct` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
          PRIMARY KEY (`c1`)
        ) ENGINE=InnoDB DEFAULT CHARSET=latin1
        ```
    2. load full data of this table into TiDB

2. What did you expect to see?

    the task paused after encountered `Error 1067: Invalid default value for 'ct'`

3. What did you see instead?

    the task still keeping the `Running` stage.

    ```
    "subTaskStatus": [
        {
             "name": "task_single",
             "stage": "Running",
             "unit": "Load",
             "result": null,
             "unresolvedDDLLockID": "",
             "load": {
                    "finishedBytes": "0",
                    "totalBytes": "145",
                    "progress": "0.00 %",
                    "metaBinlog": "(mysql-bin.000001, 957)"
              }
        }
    ],
    ```

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v1.0.5
        ```

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

fix #743

### What is changed and how it works?

call `cancel` after `Restore` returned.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
    - do operations in #743.

Code changes

 - Has exported variable/fields change

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

File: dm/worker/task_checker_test.go [hunk 1]
```diff
@@ -294,10 +294,10 @@ func (s *testTaskCheckerSuite) TestIsResumableError(c *check.C) {
 		// only DM new error is checked
 		{&tmysql.SQLError{1105, "unsupported modify column length 20 is less than origin 40", tmysql.DefaultMySQLState}, true},
 		{&tmysql.SQLError{1105, "unsupported drop integer primary key", tmysql.DefaultMySQLState}, true},
-		{nil, true},
```
Comment (csuzhangxc) [inline dm/worker/task_checker_test.go:297]: it already exists in L310.

File: dm/worker/task_checker_test.go [hunk 2]
```diff
@@ -294,10 +294,10 @@ func (s *testTaskCheckerSuite) TestIsResumableError(c *check.C) {
...
 		{terror.ErrDBExecuteFailed.Generate("file test.t3.sql: execute statement failed: USE `test_abc`;: context canceled"), true},
 		{terror.ErrDBExecuteFailed.Delegate(&tmysql.SQLError{1105, "unsupported modify column length 20 is less than origin 40", tmysql.DefaultMySQLState}, "alter table t modify col varchar(20)"), false},
 		{terror.ErrDBExecuteFailed.Delegate(&tmysql.SQLError{1105, "unsupported drop integer primary key", tmysql.DefaultMySQLState}, "alter table t drop column id"), false},
+		{terror.ErrDBExecuteFailed.Delegate(&tmysql.SQLError{1067, "Invalid default value for 'ct'", tmysql.DefaultMySQLState}, "CREATE TABLE `tbl` (`c1` int(11) NOT NULL,`ct` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创建时间',PRIMARY KEY (`c1`)) ENGINE=InnoDB DEFAULT CHARSET=latin1"), false},
```
Comment (csuzhangxc) [inline dm/worker/task_checker_test.go:300]: we may need to add an independent error codes section later.

**Comment by csuzhangxc** [comment]
@WangXiangUSTC @GMHDBJD PTAL
