### PR TITLE
pessimist: Fix Inconsistent DDL sequence error if same DDL replicate twice in sequence-sharding

### LINKED ISSUE #1785: Inconsistent DDL sequence error if same DDL replicate twice in sequence-sharding
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
sharding task: source1, table1; source2, table1; source2, table2;
```
source1, table1: ALTER TABLE ADD COLUMN a INT;

source2, table1: ALTER TABLE ADD COLUMN a INT;
source2, table1: ALTER TABLE DROP COLUMN a;
source2, table1: ALTER TABLE ADD COLUMN a INT;

source2, table2: ALTER TABLE ADD COLUMN a INT:
```
2. What did you expect to see?
first DDL: `ALTER TABLE ADD COLUMN a INT;` should be replicated
3. What did you see instead?
```
 "Message": "startLocation: [position: (mysql-bin.000001, 1937), gtid-set: 1cddbb8f-a808-11eb-9a47-0242ac110003:1-9], endLocation: [position: (mysql-bin.000001, 2054), gtid-set: 1cddbb8f-a808-11eb-9a47-0242ac110003:1-10], origin SQL: [alter table shardddl1.tb1 add new_col1 int]: detect inconsistent DDL sequence from source [first-location: position: (mysql-bin.000001, 1576), gtid-set: 1cddbb8f-a808-11eb-9a47-0242ac110003:1-7 ddls: [ALTER TABLE `shardddl`.`tb` ADD COLUMN `new_col1` INT] source: `shardddl1`.`tb1` first-location: position: (mysql-bin.000001, 1758), gtid-set: 1cddbb8f-a808-11eb-9a47-0242ac110003:1-8 ddls: [ALTER TABLE `shardddl`.`tb` DROP COLUMN `new_col1`] source: `shardddl1`.`tb1` first-location: position: (mysql-bin.000001, 1937), gtid-set: 1cddbb8f-a808-11eb-9a47-0242ac110003:1-9 ddls: [ALTER TABLE `shardddl`.`tb` ADD COLUMN `new_col1` INT] source: `shardddl1`.`tb1`], right DDL sequence should be [first-location: position: (mysql-bin.000001, 1576), gtid-set: 1cddbb8f-a808-11eb-9a47-0242ac110003:1-7 ddls: [ALTER TABLE `shardddl`.`tb` ADD COLUMN `new_col1` INT] source: `shardddl1`.`tb1` first-location: position: (mysql-bin.000001, 1758), gtid-set: 1cddbb8f-a808-11eb-9a47-0242ac110003:1-8 ddls: [ALTER TABLE `shardddl`.`tb` DROP COLUMN `new_col1`] source: `shardddl1`.`tb1`]"
```
4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
       master
        ```
5. Root Cause
When compare DDL sequences with different upstream table, [DM only concern in content, ignore order of ddl](https://github.com/pingcap/dm/blob/2e1f094cebfadb731bfad9d50db006493427e5aa/pkg/utils/common.go#L150).
When the DM meet the third DDL of source2,table1, [DM thinks it is the first DDL](https://github.com/pingcap/dm/blob/master/syncer/sharding-meta/shardmeta.go#L191-L205)

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
close #1785 

### What is changed and how it works?
if `len(source items)>len(global items)`, which means it's a new DDL for all sources, we simply add it to global items

### Check List 

Tests 

 - Integration test

### CODE REVIEW

**Review by Ehco1996 — APPROVED** [review]

File: syncer/sharding-meta/shardmeta.go [hunk 1]
```diff
@@ -188,18 +188,11 @@ func (meta *ShardingMeta) AddItem(item *DDLItem) (active bool, err error) {
...
-	for _, globalItem := range meta.global.Items {
-		if utils.CompareShardingDDLs(item.DDLs, globalItem.DDLs) {
-			found = true
-			break
-		}
-	}
-	if !found {
-		meta.global.Items = append(meta.global.Items, item)
+	global, source := meta.global, meta.sources[item.Source]
+	if len(source.Items) > len(global.Items) {
```
Comment (glorv) [inline syncer/sharding-meta/shardmeta.go:192]: Please also update the comments of this function

**Review by lance6716 — COMMENTED** [review]
requesting add a case: add column, drop column, add column, drop column, add column

**Review by lance6716 — APPROVED** [review]

**Review by glorv — APPROVED** [review]
