### PR TITLE
fix: don't forbid DM-master leader startup for unexpected DDL locks

### LINKED ISSUE #1185: dm-master can't start if optimistic shard DDL conflicts exists in etcd data
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

    in an infinite loop:
    - election become the leader
    - try start optimist
    - fail to start optimist because `there will be conflicts"
    - retire from the leader

[dm-master-can-not-setup.log](https://github.com/pingcap/dm/files/5401088/dm-master-can-not-setup.log)

3. What did you see instead?

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        master branch at least until https://github.com/pingcap/dm/commit/925c59b6a619dd7cb9ce60a986bbf53c002c7550
        ```

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

fix #1185 

### What is changed and how it works?

- don't forbid DM-master leader startup for unexpected DDL locks

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

File: pkg/parser/common.go [hunk 1]
```diff
@@ -38,10 +38,6 @@ const (
 // Parse wraps parser.Parse(), makes `parser` suitable for dm
 func Parse(p *parser.Parser, sql, charset, collation string) (stmt []ast.StmtNode, err error) {
 	stmts, warnings, err := p.Parse(sql, charset, collation)
-	if err != nil {
```
Comment (csuzhangxc) [inline pkg/parser/common.go:41]: `err` returned, and the caller will handle it so no need to log it here.

File: dm/master/scheduler/scheduler.go [hunk 2]
```diff
@@ -159,6 +159,7 @@ func NewScheduler(pLogger *log.Logger, securityCfg config.Security) *Scheduler {
 }
 
 // Start starts the scheduler for work.
+// NTOE: for logic errors, it should start without returning errors (but report via metrics or log) so that the user can fix them.
```
Comment (GMHDBJD) [inline dm/master/scheduler/scheduler.go:162]:
```suggestion
// NOTE: for logic errors, it should start without returning errors (but report via metrics or log) so that the user can fix them.

```

File: dm/master/shardddl/pessimist.go [hunk 3]
```diff
@@ -65,6 +65,7 @@ func NewPessimist(pLogger *log.Logger, taskSources func(task string) []string) *
 }
 
 // Start starts the shard DDL coordination in pessimism mode.
+// NTOE: for logic errors, it should start without returning errors (but report via metrics or log) so that the user can fix them.
```
Comment (lance6716) [inline dm/master/shardddl/pessimist.go:68]: NOTE

**Review by lance6716 — COMMENTED** [review]
rest LGTM. and maybe there's other function will let startLeaderComponent fail?

**Review by GMHDBJD — COMMENTED** [review]
LGTM

**Comment by csuzhangxc** [comment]
> and maybe there's other function will let startLeaderComponent fail

YES, but I didn't find a good way to detect this yet. 😹

**Comment by lance6716** [comment]
LGTM

**Review by lance6716 — APPROVED** [review]
