### PR TITLE
*: fix remove optimistic shard DDL lock after all tables done the operation

### LINKED ISSUE #612: optimistic lock is not removed after all tables synced (and done)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   - migrate two shard tables into one.
   - `alter table tbl1 add column c2 varchar(100)`
   - `alter table tbl2 add column c2 varchar(100)`

2. What did you expect to see?

    - add the column for the downstream.
    - add remove the lock.

3. What did you see instead?

    - the column is added
    - but the lock is not removed

```
» show-ddl-locks
{
    "result": true,
    "msg": "",
    "locks": [
        {
            "ID": "test-2-`db`.`tbl`",
            "task": "test-2",
            "mode": "optimistic",
            "owner": "",
            "DDLs": [
            ],
            "synced": [
                "mysql-replica-01-`db`.`tbl1`",
                "mysql-replica-01-`db`.`tbl2`"
            ],
            "unsynced": [
            ]
        }
    ]
}
```

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        DM with git commit 5e3aaba3a1e9b186a3c13b00f8e7a0f472d177f0.
        ```

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

fix #612 

### What is changed and how it works?

- always mark the table as done if received the done status of the DDLs operation
- remove the lock after resolved (all tables are done and have the same schema)

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity

Related changes

 - Need to be included in the release note

### CODE REVIEW

**Comment by csuzhangxc** [comment]
@WangXiangUSTC @lichunzhu PTAL

**Comment by csuzhangxc** [comment]
I added a test case for `NULL` to `NOT NULL` and some logs in https://github.com/pingcap/dm/pull/615/commits/7fbf950090deae2d1213b947e47f9abbeedcc691. no other code affetected in this commit.

File: pkg/shardddl/optimism/lock.go [hunk 1]
```diff
@@ -214,7 +219,12 @@ func (l *Lock) TryRemoveTable(source, schema, table string) bool {
 		return false
 	}
 
-	delete(l.tables[source][schema], table)
+	if ti, ok := l.tables[source][schema][table]; ok {
```
Comment (WangXiangUSTC) [inline pkg/shardddl/optimism/lock.go:222]: why add this judgment? seems that L218 already do this

Comment (csuzhangxc) [reply pkg/shardddl/optimism/lock.go]: My mistake, fixed in https://github.com/pingcap/dm/pull/615/commits/41085a7905db8ab74bde7030c91ae868e9c2f370

File: pkg/shardddl/optimism/lock.go [hunk 2]
```diff
@@ -78,6 +80,14 @@ func (l *Lock) TrySync(callerSource, callerSchema, callerTable string,
 	l.mu.Lock()
 	defer l.mu.Unlock()
 
+	defer func() {
```
[the remark this answers is not in the document]
Comment (csuzhangxc) [reply pkg/shardddl/optimism/lock.go:81]: :+1: addressed in https://github.com/pingcap/dm/pull/615/commits/2cfd562490cd0fbd5c09866cef0a35eaa22cd79f.

**Comment by WangXiangUSTC** [comment]
LGTM

File: pkg/shardddl/optimism/lock.go [hunk 3]
```diff
@@ -119,16 +128,11 @@ func (l *Lock) TrySync(callerSource, callerSchema, callerTable string,
 			}
 		}
 	}
-	l.joined = newJoined // update the current table info.
-	log.L().Info("update joined table info", zap.String("lock", l.ID), zap.Stringer("from", oldJoined), zap.Stringer("to", newJoined),
```
Comment (lichunzhu) [inline pkg/shardddl/optimism/lock.go:123]: Why do we delete this log?

Comment (csuzhangxc) [reply pkg/shardddl/optimism/lock.go:123]: table info often too long, and if the joined table info changed it will be logged later, so I deleted this duplicate one.
