### PR TITLE
shardddl: fix optimistic bug

### LINKED ISSUE #1554: optimistic bug found in chaos
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
run optimistic chaos test
2. What did you expect to see?
task succeeded
3. What did you see instead?
record below

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
fix #1554 

### What is changed and how it works?
- init miss info with init-schema
- detect SQL execute error before put info
- log short string for info
- delete drop columns after all source done
### Check List 

Tests 

 - Unit test
 - Integration test
 - chaos

### CODE REVIEW

**Comment by GMHDBJD** [comment]
PTAL

**Review by lance6716 — COMMENTED** [review]
will review later

File: syncer/optimist.go [hunk 1]
```diff
@@ -91,6 +91,12 @@ func (s *Syncer) handleQueryEventOptimistic(
 		err      error
 	)
 
+	err = s.execError.Get()
+	if err != nil {
+		ec.tctx.L().Error("error detected when executing SQL job", log.ShortError(err))
+		return nil
```
Comment (lance6716) [inline syncer/optimist.go:97]: if we didn't return error, syncer's loop will continue to get the next event. Not sure things will more complex 🤔

File: tests/shardddl3/run.sh [hunk 2]
```diff
@@ -2556,6 +2738,9 @@ function run() {
     DM_RestartMaster
 
     DM_DropAddColumn
+    DM_INIT_SCHEMA
```
Comment (lance6716) [inline tests/shardddl3/run.sh:2741]: now shardddl3 will take more than 20 minutes, and it's the slowest test. we might move it to another test.

Comment (lance6716) [reply tests/shardddl3/run.sh:2741]: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/8769/pipeline

so if CI get slower, we might can't merge all PR today 😂

File: pkg/shardddl/optimism/lock.go [hunk 3]
```diff
@@ -28,6 +28,15 @@ import (
 	"github.com/pingcap/dm/pkg/terror"
 )
 
+const (
```
Comment (lance6716) [inline pkg/shardddl/optimism/lock.go:31]: maybe define a type for it, because when I see the value of map is `int` I assume that it means the count of not dropped columns

OK to not change if need change too many place

File: syncer/syncer.go [hunk 4]
```diff
@@ -938,10 +939,18 @@ func (s *Syncer) syncDDL(tctx *tcontext.Context, queueBucket string, db *DBConn,
...
 			if len(sqlJob.ddls) == 0 {
 				ignore = true
-				tctx.L().Info("ignore shard DDLs in optimistic mode", log.WrapStringerField("info", s.optimist.PendingInfo()))
+				tctx.L().Info("ignore shard DDLs in optimistic mode", zap.Stringer("info", s.optimist.PendingInfo()))
 			}
 		}
-		if !ignore {
+
+		fp := false
+		failpoint.Inject("ExecDDLError", func() {
```
Comment (lance6716) [inline syncer/syncer.go:947]: or `failpoint.Goto("bypass")` + `failpoint.Label("bypass")`. OK not change

File: syncer/optimist.go (hunk 1 above)
Comment (GMHDBJD) [reply syncer/optimist.go:97]: `sync` and `syncDDL` will cancel the loop. Same for [other mode](https://github.com/pingcap/dm/blob/ef6138bf373249f7f9afa8a6d112f555f59e5bc4/syncer/syncer.go#L1940).

**Comment by GMHDBJD** [comment]
ha_master failed, already recorded
/run-all-tests

File: pkg/shardddl/optimism/info.go [hunk 5]
```diff
@@ -84,6 +102,40 @@ func (i Info) String() string {
 	return s
 }
 
+// ShortString returns short string of Info
+func (i *Info) ShortString() string {
```
Comment (lance6716) [inline pkg/shardddl/optimism/info.go:106]: I mean we could use value receiver, to avoid clone it in this function.

https://play.golang.org/p/qBG5ZRSFK0y

File: pkg/shardddl/optimism/keeper.go [hunk 6]
```diff
@@ -66,10 +68,21 @@ func (lk *LockKeeper) RebuildLocksAndTables(
 			}
 		}
 	}
+
+	// update missTable's table info for locks
```
Comment (lance6716) [inline pkg/shardddl/optimism/keeper.go:72]: I think we could remove `missTable`, and pass `initSchemas` here to do same logic. OK to not change because time maybe not enough

File: pkg/shardddl/optimism/lock.go [hunk 7]
```diff
@@ -263,11 +278,23 @@ func (l *Lock) TrySync(info Info, tts []TargetTable) (newDDLs []string, err erro
...
+					return ddls, cols, err2
+				} else if len(col) > 0 && l.IsDroppedColumn(info.Source, info.UpSchema, info.UpTable, col) {
+					return ddls, cols, terror.ErrShardDDLOptimismTrySyncFail.Generate(
+						l.ID, fmt.Sprintf("add column %s that wasn't fully dropped in downstream. ddl: %s", col, ddls[idx]))
+				}
+			} else {
+				if col, err2 := GetColumnName(l.ID, ddls[idx], ast.AlterTableDropColumn); err2 != nil {
+					return ddls, cols, err2
+				} else if len(col) > 0 {
+					err = l.AddDroppedColumn(info, col)
```
Comment (lance6716) [inline pkg/shardddl/optimism/lock.go:293]: from the aspect of "cols is a cache of etcd", i think we should return when error or don't append to cols

**Comment by GMHDBJD** [comment]
testSubTask.TestPauseAndResumeSubtask already recorded.
/run-all-tests

File: pkg/shardddl/optimism/info.go (hunk 5 above)
Comment (GMHDBJD) [reply pkg/shardddl/optimism/info.go:106]: But the struct between Info and LogInfo is different, unless we define another marshall method for info.

File: pkg/shardddl/optimism/lock.go [hunk 8]
```diff
@@ -559,52 +586,92 @@ func (l *Lock) IsDroppedColumn(info Info, col string) bool {
...
 	return nil
 }
 
-// DeleteColumnsByDDLs deletes the partially dropped columns that extracted from DDLs.
-// We can not remove columns from the partially dropped columns map unless this column is dropped in the downstream database,
-// that is to say, op.Done is true and ddls contains drop column DDL.
-func (l *Lock) DeleteColumnsByDDLs(ddls []string) error {
+// DeleteColumnsByOp deletes the partially dropped columns that extracted from operation.
+// We can not remove columns from the partially dropped columns map unless:
+// this column is dropped in the downstream database,
```
Comment (lance6716) [inline pkg/shardddl/optimism/lock.go:617]: is this needed? the op with DDL also has a `done` upstream shard table

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
https://github.com/pingcap/dm/blob/6791a754617dac4d9487f94c088175263d64af5c/chaos/scripts/check-case.sh#L4

https://github.com/pingcap/dm/blob/6791a754617dac4d9487f94c088175263d64af5c/.github/workflows/chaos-mesh.yml#L255

**Comment by lance6716** [comment]
/run-all-tests

unit test of etcd failed

**Comment by lance6716** [comment]
(add require-LGT1 because reviewer is not enough)

**Comment by GMHDBJD** [comment]
DM-147
/run-all-tests

**Comment by GMHDBJD** [comment]
DM-147
/run-all-tests

File: pkg/shardddl/optimism/column.go [hunk 9]
```diff
@@ -22,8 +24,9 @@ import (
 
 // GetAllDroppedColumns gets the all partially dropped columns.
 // return lockID -> column-name -> source-id -> upstream-schema-name -> upstream-table-name
```
Comment (lichunzhu) [inline pkg/shardddl/optimism/column.go:26]: Please note what does `DropColumnStage` mean in comments.

File: dm/common/common.go [hunk 10]
```diff
@@ -80,7 +80,7 @@ var (
 	// k/v: Encode(task-name, downstream-schema-name, downstream-table-name) -> table schema.
 	ShardDDLOptimismInitSchemaKeyAdapter KeyAdapter = keyHexEncoderDecoder("/dm-master/shardddl-optimism/init-schema/")
 	// ShardDDLOptimismDroppedColumnsKeyAdapter is used to store the columns that are not fully dropped
-	// k/v: Encode(task-name, downstream-schema-name, downstream-table-name, column-name, source-id, upstream-schema-name, upstream-table-name) -> empty
```
Comment (lichunzhu) [inline dm/common/common.go:83]: Maybe we should write what's this `integer`'s usage?

Comment (lichunzhu) [reply dm/common/common.go:83]: Besides, if you want to change this key's format, this part must be revised, too.
https://github.com/pingcap/dm/blob/master/pkg/shardddl/optimism/ops.go#L80

**Review by lichunzhu — COMMENTED** [review]
I will take a further review later.

File: pkg/shardddl/optimism/column.go (hunk 9 above)
Comment (GMHDBJD) [reply pkg/shardddl/optimism/column.go:26]: comments in https://github.com/pingcap/dm/blob/5ae19df6c531537f61d8b961bbbf526fe09fab80/pkg/shardddl/optimism/lock.go#L31-L40

File: dm/common/common.go (hunk 10 above)
Comment (GMHDBJD) [reply dm/common/common.go:83]: > Maybe we should write what's this `integer`'s usage?

ditto https://github.com/pingcap/dm/blob/5ae19df6c531537f61d8b961bbbf526fe09fab80/pkg/shardddl/optimism/lock.go#L31-L40

Comment (GMHDBJD) [reply dm/common/common.go:83]: > Besides, if you want to change this key's format, this part must be revised, too.
> https://github.com/pingcap/dm/blob/master/pkg/shardddl/optimism/ops.go#L80

address in bf05a9d

**Comment by lichunzhu** [comment]
please fix the lint
