### PR TITLE
syncer: update binlog filename when receive fake rotate event

### LINKED ISSUE #1830: binlog file name not right when upstream mysql master-slave switching
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

mysql 1 127.0.0.1:3306
mysql2 127.0.0.1:3307

The two mysql are from VIP (127.0.0.2), mysql1 is the msater mysql2 is the slave.

DM starts syncing from VIP (127.0.0.2) to the binlog file. `bin.0000009`.
At this point in time, the checkpoint in DM is `bin.0000009`.

now master-slave switching, new master is mysql2

The binlog file for master 2 again starts at `bin.000001`

But DM does not update the binlog filename in the checkpoint and it still shows "bin.000009", until mysql2(new master) sends a rotate event to DM

after this rotate event, both DM and master's current binlog file is `bin.0.00002`

2. What did you expect to see?

DM update binlog file name correctly after master-slave switching

3. What did you see instead?
as title

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

    v2.0.4

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible
截屏2021-07-02 下午1 49 04

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve? 
close #1830 

### What is changed and how it works?

as title,  but we only update location binlog filename when enable GTID mode.

### Check List 

Tests 
 - Integration test
 - Manual test (add detailed scripts or steps below)

Code changes

 - Has exported function/method change

Side effects

 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

**Comment by Ehco1996** [comment]
/hold  
need it test

File: pkg/binlog/reader/util.go [hunk 1]
```diff
@@ -27,6 +27,7 @@ import (
 	"github.com/pingcap/dm/pkg/gtid"
 	"github.com/pingcap/dm/pkg/log"
 	"github.com/pingcap/dm/pkg/terror"
+	du "github.com/pingcap/dm/pkg/utils"
```
Comment (lance6716) [inline pkg/binlog/reader/util.go:30]: why rename this package

File: syncer/syncer.go [hunk 2]
```diff
@@ -1740,10 +1738,23 @@ type eventContext struct {
 
 // TODO: Further split into smaller functions and group common arguments into a context struct.
 func (s *Syncer) handleRotateEvent(ev *replication.RotateEvent, ec eventContext) error {
-	if ec.header.Timestamp == 0 || ec.header.LogPos == 0 { // fake rotate event
-		if string(ev.NextLogName) <= ec.lastLocation.Position.Name {
+	failpoint.Inject("MakeFakeRotateEvent", func(val failpoint.Value) {
+		ec.header.LogPos = 0
```
Comment (lance6716) [inline syncer/syncer.go:1742]: set Timestamp?

File: syncer/syncer.go [hunk 3]
```diff
@@ -1740,10 +1738,23 @@ type eventContext struct {
...
+		ev.NextLogName = []byte(val.(string))
+		ec.tctx.L().Info("MakeFakeRotateEvent", zap.String("fake filen name", string(ev.NextLogName)))
+	})
+
+	if utils.IsFakeRotateEvent(ec.header) {
+		if fileName := string(ev.NextLogName); fileName <= ec.lastLocation.Position.Name {
```
Comment (lance6716) [inline syncer/syncer.go:1748]: new binlog filename of new server may not <= old filename, 

mysqlbin.xxx vs bin.xxx

File: syncer/syncer.go (hunk 2 above)
Comment (Ehco1996) [reply syncer/syncer.go:1742]: when logPos is 0, this event will be treated as a fake roate event

File: syncer/syncer.go (hunk 3 above)
Comment (Ehco1996) [reply syncer/syncer.go:1748]: i not sure about this, you can check this [commit](https://github.com/pingcap/dm/commit/b6a6e585b8cc523fa406758c5fb2ef86801f4c89)

Comment (lance6716) [reply syncer/syncer.go:1748]: that commit is to handle this case:

When we restart synchronization from an early position, DM will see lots of oudated rotate event (we could determine if they are outdated by comparing the filename with global checkpoint). For some reason (I forgot) DM will update table checkpoint to that outdated position. Because the position is older than global checkpoint, DM will panic https://github.com/pingcap/dm/blob/18918ed3d4813a61a43cabf04e5e1fc28bfd5a43/syncer/checkpoint.go#L363

File: syncer/syncer.go [hunk 4]
```diff
@@ -3177,7 +3188,7 @@ func (s *Syncer) adjustGlobalPointGTID(tctx *tcontext.Context) (bool, error) {
 			zap.String("adjusted_gtid", gs.String()), zap.Error(err))
 		return false, err
 	}
-	s.checkpoint.SaveGlobalPoint(location)
+	s.saveGlobalPoint(location)
```
Comment (lance6716) [inline syncer/syncer.go:3191]: what's the purpose of this change

File: tests/fake_rotate_event/data/db1.prepare.sql [hunk 5]
```diff
@@ -0,0 +1,19 @@
+drop database if exists `fake_rotate_event`;
+
+reset master;
```
Comment (lance6716) [inline tests/fake_rotate_event/data/db1.prepare.sql:3]: ditto

File: tests/fake_rotate_event/run.sh [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+
+	echo "kill dm-worker1"
+	ps aux | grep dm-worker1 | awk '{print $2}' | xargs kill || true
+	check_port_offline $WORKER1_PORT 20
+
+	# make fake rotate event and rewrite binlog filename to mysql-bin.000001
+	export GO_FAILPOINTS='github.com/pingcap/dm/syncer/MakeFakeRotateEvent=return("mysql-bin.000001")'
+	run_dm_worker $WORK_DIR/worker1 $WORKER1_PORT $cur/conf/dm-worker1.toml
+	check_rpc_alive $cur/../bin/check_worker_online 127.0.0.1:$WORKER1_PORT
+
```
Comment (lance6716) [inline tests/fake_rotate_event/run.sh:46]: revert GO_FAILPOINTS

File: tests/fake_rotate_event/run.sh [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+	# make a fake rotae event
+	run_sql_source1 "flush logs;"
+	run_sql_source1 "use $db;alter table $tb add column info2 varchar(40);" # trigger a flush job
```
Comment (lance6716) [inline tests/fake_rotate_event/run.sh:49]: we could create a sql file since there're many statements

File: tests/fake_rotate_event/run.sh [hunk 8]
```diff
@@ -0,0 +1,65 @@
...
+	run_sql_source1 "use $db; insert into $tb values (4, 4, 4,'info')"
+	run_sql_tidb_with_retry "select count(1) from ${db}.${tb}" "count(1): 4"
+
+	$PWD/bin/dmctl.test DEVEL --master-addr=127.0.0.1:$MASTER_PORT query-status test >$WORK_DIR/binlog-status.log
```
Comment (lance6716) [inline tests/fake_rotate_event/run.sh:53]: don't know what you want to test. We should check filename in query-status?

File: tests/fake_rotate_event/run.sh [hunk 9]
```diff
@@ -0,0 +1,65 @@
...
+	# make fake rotate event and rewrite binlog filename to mysql-bin.000001
+	export GO_FAILPOINTS='github.com/pingcap/dm/syncer/MakeFakeRotateEvent=return("mysql-bin.000001")'
+	run_dm_worker $WORK_DIR/worker1 $WORKER1_PORT $cur/conf/dm-worker1.toml
+	check_rpc_alive $cur/../bin/check_worker_online 127.0.0.1:$WORKER1_PORT
+
+	# make a fake rotae event
+	run_sql_source1 "flush logs;"
+	run_sql_source1 "use $db;alter table $tb add column info2 varchar(40);" # trigger a flush job
+	run_sql_source1 "use $db; insert into $tb values (4, 4, 4,'info')"
+	run_sql_tidb_with_retry "select count(1) from ${db}.${tb}" "count(1): 4"
```
Comment (lance6716) [inline tests/fake_rotate_event/run.sh:51]: use sync_diff rather than plain query, unless sync_diff can't handle this check

File: syncer/syncer.go (hunk 4 above)
Comment (Ehco1996) [reply syncer/syncer.go:3205]: to ensure that there is only one function in the SaveGlobalPoint and this doesn't seem to break the original logic?

please correct me if I'm wrong😉

File: tests/fake_rotate_event/data/db1.prepare.sql (hunk 5 above)
Comment (Ehco1996) [reply tests/fake_rotate_event/data/db1.prepare.sql:3]: do what?

File: tests/fake_rotate_event/run.sh [hunk 10]
```diff
@@ -0,0 +1,64 @@
...
+	run_sql_source1 "flush logs;"
+	run_sql_source1 "use $db;alter table $tb add column info2 varchar(40);" # trigger a flush job
+	run_sql_source1 "use $db; insert into $tb values (4, 4, 4,'info')"
+	check_sync_diff $WORK_DIR $cur/conf/diff_config.toml
+
+	# check syncer's binlog filename same with fake rotate file name
+	run_dm_ctl_with_retry $WORK_DIR "127.0.0.1:$MASTER_PORT" \
+		"query-status test" \
+		"\"result\": true" 2 \
+		"mysql-bin.9999999999" 1
```
Comment (lance6716) [inline tests/fake_rotate_event/run.sh:53]: 9999999999 is of course greater than 000001, so not a test.

**Review by lance6716 — APPROVED** [review]

**Comment by GMHDBJD** [comment]
I think we can test it in upstream_switch case

**Comment by Ehco1996** [comment]
> I think we can test it in upstream_switch case

added in https://github.com/pingcap/dm/pull/1848/commits/c95110bb30b0fb499ed37614c25020daae8b934a

File: tests/upstream_switch/case.sh [hunk 11]
```diff
@@ -140,6 +148,7 @@ function gen_incr_data() {
 		exec_sql $host2 "insert into ${db}.${tb} values($i,$i,$i);"
 	done
 
+	# make  master slave switch
```
Comment (lance6716) [inline tests/upstream_switch/case.sh:151]:
```suggestion
	# make master slave switch
```

File: tests/upstream_switch/case.sh [hunk 12]
```diff
@@ -217,6 +227,48 @@ function test() {
...
+	check_master
+	clean_data
+	setup_replica
+	gen_full_data
+	run_dm_components_and_create_sources
+	start_task
+
+	# flush mysql8 master binlog files -> mysql-bin.000002
+	exec_sql $host1 "flush logs;"
+	# flush mysql8 master binlog files -> mysql-bin.000004
```
Comment (lance6716) [inline tests/upstream_switch/case.sh:244]: one is master, one is slave?

File: tests/upstream_switch/case.sh [hunk 13]
```diff
@@ -217,6 +227,48 @@ function test() {
...
+
+	# make a flush job to dm
+	exec_sql $host1 "alter table ${db}.${tb} add column c int;"
+	exec_sql $host2 "alter table ${db}.${tb} add column c int;"
+
+	check_sync_diff $WORK_DIR $CUR/conf/diff_config.toml
+	# mysql8 new master's binlog file still is mysql-bin.000001
+	run_dm_ctl_with_retry $WORK_DIR "127.0.0.1:$MASTER_PORT" \
+		"query-status task_pessimistic " \
+		"mysql-bin.000001" 2
```
Comment (lance6716) [inline tests/upstream_switch/case.sh:261]: already flushed to 000002?

File: tests/upstream_switch/case.sh [hunk 14]
```diff
@@ -217,6 +227,48 @@ function test() {
...
+
+	docker-compose -f $CUR/docker-compose.yml unpause mysql8_master
+	clean_task
+	echo "CASE=test_binlog_filename_change_when_enable_gtid success"
+
```
Comment (lance6716) [inline tests/upstream_switch/case.sh:266]:
```suggestion
```

**Review by lance6716 — CHANGES_REQUESTED** [review]

File: tests/upstream_switch/case.sh (hunk 12 above)
Comment (Ehco1996) [reply tests/upstream_switch/case.sh:244]: $host1 is svip of two mysql and it's always point to master

File: tests/upstream_switch/case.sh (hunk 13 above)
Comment (Ehco1996) [reply tests/upstream_switch/case.sh:261]: after one switch, source-2 binlog still is 00001

but source-1's binlog is 00002

File: tests/upstream_switch/case.sh [hunk 15]
```diff
@@ -217,6 +227,47 @@ function test() {
...
+	# make mysql8 master slave switch
+	docker-compose -f $CUR/docker-compose.yml pause mysql8_master
+	wait_mysql $host2 2
+
+	# make a flush job to dm
+	exec_sql $host1 "alter table ${db}.${tb} add column c int;"
+	exec_sql $host2 "alter table ${db}.${tb} add column c int;"
+
+	check_sync_diff $WORK_DIR $CUR/conf/diff_config.toml
+	# mysql8 new master's binlog file still is mysql-bin.000001
```
Comment (lance6716) [inline tests/upstream_switch/case.sh:258]: why we flush mysql 5.7, did you want to test it but forget?

**Review by lance6716 — COMMENTED** [review]
rest lgtm

File: tests/upstream_switch/case.sh (hunk 15 above)
Comment (Ehco1996) [reply tests/upstream_switch/case.sh:258]: i want last query-status result source-1's binlog filnname is not `binlog.00001` so that i can check and count source-2's binlog filename

Comment (lance6716) [reply tests/upstream_switch/case.sh:258]: the number of `binlog.00001` will be 4 not 2 then

**Comment by GMHDBJD** [comment]
Can you add start-relay command for source2? Since enable-relay not working now and we also need to test it.

**Comment by Ehco1996** [comment]
/hold  

when start-relay, filename  getting weird.
```
            "subTaskStatus": [
                {
                    "name": "task_pessimistic",
                    "stage": "Running",
                    "unit": "Sync",
                    "result": null,
                    "unresolvedDDLLockID": "",
                    "sync": {
                        "totalEvents": "1",
                        "totalTps": "0",
                        "recentTps": "0",
                        "masterBinlog": "(mysql-bin.000001, 30830)",
                        "masterBinlogGtid": "5e52a3f4-e483-11eb-afeb-0242ac1c8006:1-102,5e5966ac-e483-11eb-be47-0242ac1c8007:1",
                        "syncerBinlog": "(mysql-bin|000002.000001, 30690)",
                        "syncerBinlogGtid": "5e52a3f4-e483-11eb-afeb-0242ac1c8006:1-102",
                        "blockingDDLs": [
                        ],
                        "unresolvedGroups": [
                        ],
                        "synced": false,
                        "binlogType": "local",
                        "secondsBehindMaster": "19"
                    }
                }
            ]
```

**Comment by GMHDBJD** [comment]
> /hold
> 
> when start-relay, filename getting weird.
> 
> ```
>             "subTaskStatus": [
>                 {
>                     "name": "task_pessimistic",
>                     "stage": "Running",
>                     "unit": "Sync",
>                     "result": null,
>                     "unresolvedDDLLockID": "",
>                     "sync": {
>                         "totalEvents": "1",
>                         "totalTps": "0",
>                         "recentTps": "0",
>                         "masterBinlog": "(mysql-bin.000001, 30830)",
>                         "masterBinlogGtid": "5e52a3f4-e483-11eb-afeb-0242ac1c8006:1-102,5e5966ac-e483-11eb-be47-0242ac1c8007:1",
>                         "syncerBinlog": "(mysql-bin|000002.000001, 30690)",
>                         "syncerBinlogGtid": "5e52a3f4-e483-11eb-afeb-0242ac1c8006:1-102",
>                         "blockingDDLs": [
>                         ],
>                         "unresolvedGroups": [
>                         ],
>                         "synced": false,
>                         "binlogType": "local",
>                         "secondsBehindMaster": "19"
>                     }
>                 }
>             ]
> ```

That meets with expectations. https://pingcap.com/blog-cn/dm-source-code-reading-6/#%E4%B8%BB%E4%BB%8E%E5%88%87%E6%8D%A2%E6%94%AF%E6%8C%81

**Comment by GMHDBJD** [comment]
> 
```
  "masterBinlog": "(mysql-bin.000001, 30830)",
                        "masterBinlogGtid": "5e52a3f4-e483-11eb-afeb-0242ac1c8006:1-102,5e5966ac-e483-11eb-be47-0242ac1c8007:1",
                        "syncerBinlog": "(mysql-bin|000002.000001, 30690)",
                        "syncerBinlogGtid": "5e52a3f4-e483-11eb-afeb-0242ac1c8006:1-102",
```
gtid and pos seems still not match.

**Comment by lance6716** [comment]
> > 
> 
> ```
>   "masterBinlog": "(mysql-bin.000001, 30830)",
>   "masterBinlogGtid": "5e52a3f4-e483-11eb-afeb-0242ac1c8006:1-102,5e5966ac-e483-11eb-be47-0242ac1c8007:1",
>   "syncerBinlog": "(mysql-bin|000002.000001, 30690)",
>   "syncerBinlogGtid": "5e52a3f4-e483-11eb-afeb-0242ac1c8006:1-102",
> ```
> 
> gtid and pos seems still not match.

"secondsBehindMaster": "19" 🤔

**Comment by Ehco1996** [comment]
/unhold

> > 
> 
> ```
>   "masterBinlog": "(mysql-bin.000001, 30830)",
>   "masterBinlogGtid": "5e52a3f4-e483-11eb-afeb-0242ac1c8006:1-102,5e5966ac-e483-11eb-be47-0242ac1c8007:1",
>   "syncerBinlog": "(mysql-bin|000002.000001, 30690)",
>   "syncerBinlogGtid": "5e52a3f4-e483-11eb-afeb-0242ac1c8006:1-102",
> ```
> 
> gtid and pos seems still not match.

I find that sometimes the gitid set doesn't match the master's but the data is still the same, maybe another pr to fix this. @GMHDBJD

**Comment by Ehco1996** [comment]
> > > 
> > 
> > 
> > ```
> >   "masterBinlog": "(mysql-bin.000001, 30830)",
> >   "masterBinlogGtid": "5e52a3f4-e483-11eb-afeb-0242ac1c8006:1-102,5e5966ac-e483-11eb-be47-0242ac1c8007:1",
> >   "syncerBinlog": "(mysql-bin|000002.000001, 30690)",
> >   "syncerBinlogGtid": "5e52a3f4-e483-11eb-afeb-0242ac1c8006:1-102",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gtid and pos seems still not match.
> 
> "secondsBehindMaster": "19" 🤔

When the old master node goes down, it takes some time for keepalived to make the master-slave switch, so maybe this cause the lag , further investigation may be required

**Review by lance6716 — APPROVED** [review]

File: syncer/syncer.go (hunk 3 above)
Comment (lichunzhu) [reply syncer/syncer.go:1765]: `mysqlbin.999999` vs `mysqlbin.1000000` 🤔

Comment (lance6716) [reply syncer/syncer.go:1765]: should use `CompareBinlogFileName`

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
waiting https://github.com/pingcap/dm/pull/1848#discussion_r670238013

File: tests/fake_rotate_event/run.sh (hunk 7 above)
Comment (Ehco1996) [reply tests/fake_rotate_event/run.sh:45]: there is only three sql , put them into a file maybe not be easy to read

File: syncer/syncer.go (hunk 3 above)
Comment (Ehco1996) [reply syncer/syncer.go]: fixed in  https://github.com/pingcap/dm/pull/1848/commits/d8cac8507fb9f55642f5aafb0083ab9307099010
