### PR TITLE
syncer: refine lag metric

### LINKED ISSUE #2004: replicate lag in grafana shown the incrorrect info
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

- create a dm cluster task  to replicate two upstream mysql data.
- pasue the task, add 450GB incremental data in upstream
- resume the dm task.

2. What did you expect to see?
grafana will show the correct info

3. What did you see instead?
image
image
image
image
 

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        2.0.6
        ```

    - Upstream MySQL/MariaDB server version:

        ```
        5.7/8.0.2
        ```

    - Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
       5.1.1
        ```

    - How did you deploy DM: DM-Ansible or manually?

        ```
       DM-Ansible
        ```

    - Other interesting information (system version, hardware config, etc):

        >
        >

5. current status of DM cluster (execute `query-status` in dmctl)

6. Operation logs
   - Please upload `dm-worker.log` for every DM-worker instance if possible
   - Please upload `dm-master.log` if possible
   - Other interesting logs
   - Output of dmctl's commands with problems
   
7. Configuration of the cluster and the task
   - `dm-worker.toml` for every DM-worker instance if possible
   - `dm-master.toml` for DM-master if possible
   - task config, like `task.yaml` if possible
   - `inventory.ini` if deployed by DM-Ansible

8. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus for DM if possible

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve? 

close https://github.com/pingcap/dm/issues/1879
close #2004 

### What is changed and how it works?

* use cron job (100ms) to update lag metric
* ~~add log when lag > 1 `[2021/08/30 13:01:50.637 +08:00] [WARN] [syncer.go:890] ["current replication lag greater than 1(s)"] [task=test-3307] [unit="binlog replication"] ["lag in seconds"=268]`~~
* ~~add promtheus alert when lag greater than 1s~~

~~**not firing:** 截屏2021-08-30 上午11 41 07~~

~~**firing:** 截屏2021-08-30 下午12 58 07~~

see more detail in [here](https://docs.google.com/document/d/1Jhm6dWJXir_tpeQ_9QolwYQSjSodefo0Scj7p2WqF4I/edit)

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

Side effects

 - Possible performance regression
 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

File: syncer/syncer.go [hunk 1]
```diff
@@ -223,9 +223,9 @@ type Syncer struct {
 	// `lower_case_table_names` setting of upstream db
 	SourceTableNamesFlavor utils.LowerCaseTableNamesFlavor
 
-	tsOffset                  atomic.Int64             // time offset between upstream and syncer, DM's timestamp - MySQL's timestamp
-	secondsBehindMaster       atomic.Int64             // current task delay second behind upstream
-	workerLagMap              map[string]*atomic.Int64 // worker's sync lag key:WorkerLagKey val: lag
+	tsOffset                  atomic.Int64    // time offset between upstream and syncer, DM's timestamp - MySQL's timestamp
+	secondsBehindMaster       atomic.Int64    // current task delay second behind upstream
+	workerLagMap              []*atomic.Int64 // worker's sync lag map, note that idx=0 is ddl lag and idx=1 is skip lag,sql worker lag idx=(queue id + 2)
```
Comment (Ehco1996) [inline syncer/syncer.go:228]: change to array

File: syncer/syncer.go [hunk 2]
```diff
@@ -264,7 +264,13 @@ func NewSyncer(cfg *config.SubTaskConfig, etcdClient *clientv3.Client) *Syncer {
 		syncer.sgk = NewShardingGroupKeeper(syncer.tctx, cfg)
 	}
 	syncer.recordedActiveRelayLog = false
-	syncer.workerLagMap = make(map[string]*atomic.Int64, cfg.WorkerCount+2) // map size = WorkerCount + ddlkey + skipkey
+	syncer.workerLagMap = make([]*atomic.Int64, cfg.WorkerCount+2) // size = ddl + skip + workerCount
```
Comment (Ehco1996) [inline syncer/syncer.go:267]: didto

File: syncer/syncer.go [hunk 3]
```diff
@@ -863,25 +869,42 @@ func (s *Syncer) updateReplicationLag(job *job, lagKey string) {
...
+		if wl := s.workerLagMap[idx].Load(); wl > lag {
 			lag = wl
 		}
 	}
 	metrics.ReplicationLagHistogram.WithLabelValues(s.cfg.Name, s.cfg.SourceID, s.cfg.WorkerName).Observe(float64(lag))
 	metrics.ReplicationLagGauge.WithLabelValues(s.cfg.Name, s.cfg.SourceID, s.cfg.WorkerName).Set(float64(lag))
 	s.secondsBehindMaster.Store(lag)
+
+	if lag > 1 {
+		s.tctx.L().Warn("current replication lag greater than 1(s)",
```
Comment (Ehco1996) [inline syncer/syncer.go:890]: this maybe cause too much log when lag is alway large than 1 ? and this may cause high IO pressure 🤔

**Comment by lance6716** [comment]
DM is in fact not identified as a real-time sychronization tool, adding "1s" lag alert is too tight. I think maybe 10 minutes is OK

File: syncer/syncer.go (hunk 3 above)
Comment (lance6716) [reply syncer/syncer.go:887]: better to remove it because if there're many backlog binlog files it will print many log

File: syncer/syncer.go [hunk 4]
```diff
@@ -223,9 +223,9 @@ type Syncer struct {
 	// `lower_case_table_names` setting of upstream db
 	SourceTableNamesFlavor utils.LowerCaseTableNamesFlavor
 
-	tsOffset                  atomic.Int64             // time offset between upstream and syncer, DM's timestamp - MySQL's timestamp
-	secondsBehindMaster       atomic.Int64             // current task delay second behind upstream
-	workerLagMap              map[string]*atomic.Int64 // worker's sync lag key:WorkerLagKey val: lag
+	tsOffset                  atomic.Int64    // time offset between upstream and syncer, DM's timestamp - MySQL's timestamp
+	secondsBehindMaster       atomic.Int64    // current task delay second behind upstream
+	workerLagArray            []*atomic.Int64 // worker's sync lag array, note that idx=0 is ddl lag and idx=1 is skip lag,sql worker lag idx=(queue id + 2)
```
Comment (glorv) [inline syncer/syncer.go:228]:
```suggestion
	workerLagArray            []*atomic.Int64 // worker's sync lag array, note that idx=0 is skip lag and idx=1 is ddl lag,sql worker lag idx=(queue id + 2)
```
According to the previous defined constants

File: syncer/syncer.go [hunk 5]
```diff
@@ -863,25 +866,37 @@ func (s *Syncer) updateReplicationLag(job *job, lagKey string) {
...
+
+	failpoint.Inject("ShowLagInLog", func(v failpoint.Value) {
+		minLag := v.(int)
+		if int(lag) >= minLag {
+			s.tctx.L().Info("ShowLagInLog", zap.Int64("lag", lag))
+		}
+	})
+
+	// reset ddl / skip lag in case of ddl / skip lag is never updated
+	if lag == s.workerLagArray[ddlLagIdx].Load() {
```
Comment (glorv) [inline syncer/syncer.go:894]: This reset seems not reasonable. If a ddl need long time to execute and dml/skip have 0 latency. Then after the first 100ms,the ddl lag is zeroed, so after that the overall latency is 0 which is not reflect the truth. 

I suggest the ddl lag stores the ts that ddl job started and reset it to 0 when ddl job is finished. So we can calculate the true latency when execute a slow ddl event.

Comment (Ehco1996) [reply syncer/syncer.go]: It's a good idea and we can get one step closer
since there will also be some DML statements that execute very slowly, we can standardise the lag calculation logic for both DDL and DML , in https://github.com/pingcap/dm/pull/2060/commits/deaf4b47712631044d0191a5c680777bde05d144

File: syncer/syncer.go [hunk 6]
```diff
@@ -1352,6 +1364,14 @@ func (s *Syncer) syncDML(
 		if len(jobs) == 0 {
 			return 0, nil
 		}
+		// set this batch of job TS when this batch is started.
+		s.updateReplicationJobTS(jobs[0], workerJobIdx)
```
Comment (glorv) [inline syncer/syncer.go:1368]: How about move this to L1436, we can update the ts only when we receive the first job, this should be more accurate and reasonable.
```
for {
  ....
  case sqlJob, ok := <-jobChan:
     if len(jobs) == 0 {
      s.updateReplicationJobTS(sqlJob, workerJobIdx)
    }
}
```

**Review by glorv — COMMENTED** [review]
rest LGTM

File: syncer/syncer.go (hunk 6 above)
Comment (Ehco1996) [reply syncer/syncer.go]: fixed in https://github.com/pingcap/dm/pull/2060/commits/6b1bfb9bc0cfa1d0cb06ea150f8f5b3dcd2717bb

**Review by glorv — APPROVED** [review]

File: syncer/syncer.go [hunk 7]
```diff
@@ -846,42 +849,45 @@ func (s *Syncer) calcReplicationLag(headerTS int64) int64 {
...
+		minLag := v.(int)
+		if int(lag) >= minLag {
+			s.tctx.L().Info("ShowLagInLog", zap.Int64("lag", lag))
+		}
+	})
+
+	// reset skip job TS in case of skip job TS is never updated
+	if minTS == s.workerJobTSArray[skipJobIdx].Load() {
+		s.workerJobTSArray[skipJobIdx].Store(0)
+	}
```
[the remark this answers is not in the document]
Comment (Ehco1996) [reply syncer/syncer.go:890]: ddl job's TS will reset when job is finished https://github.com/Ehco1996/dm/blob/6b1bfb9bc0cfa1d0cb06ea150f8f5b3dcd2717bb/syncer/syncer.go#L1298

File: syncer/job.go [hunk 8]
```diff
@@ -174,6 +174,10 @@ func queueBucketName(queueID int) string {
 	return fmt.Sprintf("q_%d", queueID%defaultBucketCount)
 }
 
-func dmlWorkerLagKey(queueID int) string {
-	return fmt.Sprintf("lag_%d", queueID)
+func dmlWorkerJobIdx(queueID int) int {
+	return queueID + 2
```
[the remark this answers is not in the document]
Comment (Ehco1996) [reply syncer/job.go]: added in https://github.com/pingcap/dm/pull/2060/commits/78969d80f91786f56c945ed0bb511f4a8e0cc5b3

**Review by lichunzhu — COMMENTED** [review]
Rest LGTM

**Comment by Ehco1996** [comment]
@lichunzhu comments are all resolved PTAL

**Review by lichunzhu — APPROVED** [review]
My suggestion has broken the lint rules.. Remember to fix gofumpt
