### PR TITLE
optimist: only update table info if no conflict

### LINKED ISSUE #1484: handle-error replace can't handle default value conflict in optimistic mode.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
```
run_sql_source1 "alter table ${shardddl1}.${tb1} add new_col1 int default 0;"
run_sql_source2 "alter table ${shardddl1}.${tb1} add new_col1 int default -1;" // conflict detect
```
replace source2's ddl
```
handle-error test replace -s mysql-replica-02 "alter table shardddl1.tb1 add new_col1 int default 0;"
```

2. What did you expect to see?
task continue
3. What did you see instead?
error occur
```
there will be conflicts if DDLs [ALTER TABLE `shardddl`.`tb` ADD COLUMN `new_col1` INT DEFAULT 0] are applied to the downstream. old table info: CREATE TABLE `tbl`(`id` INT(11) NOT NULL, `new_col1` INT(11) DEFAULT -1, PRIMARY KEY (`id`)) CHARSET LATIN1 COLLATE LATIN1_BIN, new table info: CREATE TABLE `tbl`(`id` INT(11) NOT NULL, `new_col1` INT(11) DEFAULT 0, PRIMARY KEY (`id`)) CHARSET LATIN1 COLLATE LATIN1_BIN, RawCause: at tuple index 2: at map key \"new_col1\": at tuple index 0: distinct singletons (-1 vs 0)
```
4. Root cause
we save new [table info](https://github.com/pingcap/dm/blob/cd9e90106c58674c1d864d2a21fa450f41fa1591/pkg/shardddl/optimism/lock.go#L127) before [detect conflict](https://github.com/pingcap/dm/blob/cd9e90106c58674c1d864d2a21fa450f41fa1591/pkg/shardddl/optimism/lock.go#L160)
when replace ddl, new ddl will be [conflict](https://github.com/pingcap/dm/blob/cd9e90106c58674c1d864d2a21fa450f41fa1591/pkg/shardddl/optimism/lock.go#L121) with previous error ddl

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
close #1484 

### What is changed and how it works?
If a ddl conflict with previous one, do not update table info in master, so we can use handle-error replace to replace a new ddl and no conflict.

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

File: pkg/shardddl/optimism/lock_test.go [hunk 1]
```diff
@@ -989,20 +1003,8 @@ func (t *testLock) TestLockTrySyncConflictIntrusive(c *C) {
 	c.Assert(DDLs, DeepEquals, []string{})
 	c.Assert(l.versions, DeepEquals, vers)
 	cmp, err = l.tables[source][db][tbls[1]].Compare(l.Joined())
-	c.Assert(err, ErrorMatches, ".*at tuple index.*")
-	c.Assert(cmp, Equals, 0)
-
-	// TrySync for the second table to drop the non-conflict column, the conflict should still exist.
```
Comment (lance6716) [inline pkg/shardddl/optimism/lock_test.go:995]: seems this case and DDLs3 could keep as before

**Review by lance6716 — COMMENTED** [review]
rest LGTM

**Review by lichunzhu — COMMENTED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]

File: pkg/shardddl/optimism/lock.go [hunk 2]
```diff
@@ -180,8 +185,9 @@ func (l *Lock) TrySync(callerSource, callerSchema, callerTable string,
 		nextTable = schemacmp.Encode(newTI)
 		// special case: check whether DDLs making the schema become part of larger and another part of smaller.
 		if _, err = prevTable.Compare(nextTable); err != nil {
-			return emptyDDLs, terror.ErrShardDDLOptimismTrySyncFail.Delegate(
+			err = terror.ErrShardDDLOptimismTrySyncFail.Delegate(
```
Comment (lichunzhu) [inline pkg/shardddl/optimism/lock.go:188]: Do we need this? err is a returned variable in L95.

Comment (GMHDBJD) [reply pkg/shardddl/optimism/lock.go]: address in dfab765

**Review by lance6716 — APPROVED** [review]
