### PR TITLE
fix(load): stop goroutines after restore returned (#744)

### LINKED ISSUE #743: the stage of load unit is still running after encountered "Error 1067: Invalid default value for 'ct'"
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

    0. set `NO_ZERO_DATE` `sql_mode` for the downstream TiDB.
    1. create a table with `DEFAULT '0000-00-00 00:00:00'`
        ```sql
        CREATE TABLE `tbl` (
          `c1` int(11) NOT NULL,
          `ct` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
          PRIMARY KEY (`c1`)
        ) ENGINE=InnoDB DEFAULT CHARSET=latin1
        ```
    2. load full data of this table into TiDB

2. What did you expect to see?

    the task paused after encountered `Error 1067: Invalid default value for 'ct'`

3. What did you see instead?

    the task still keeping the `Running` stage.

    ```
    "subTaskStatus": [
        {
             "name": "task_single",
             "stage": "Running",
             "unit": "Load",
             "result": null,
             "unresolvedDDLLockID": "",
             "load": {
                    "finishedBytes": "0",
                    "totalBytes": "145",
                    "progress": "0.00 %",
                    "metaBinlog": "(mysql-bin.000001, 957)"
              }
        }
    ],
    ```

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v1.0.5
        ```

### PR DESCRIPTION
**Pull request by csuzhangxc**
- cherry-pick #744 manually.
- include error codes in the response of `query-status`.

### What problem does this PR solve? 

fix #743

### What is changed and how it works?

call `cancel` after `Restore` returned.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
    - do operations in #743.

Code changes

 - Has exported variable/fields change

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

File: dm/worker/status.go [hunk 1]
```diff
@@ -194,16 +194,16 @@ func (w *Worker) Error(stName string) []*pb.SubTaskError {
...
+// error message will be displayed in `query-status`, because the `Error` field contains enough error information.
 func statusProcessResult(pr *pb.ProcessResult) *pb.ProcessResult {
 	if pr == nil {
 		return nil
 	}
 	result := proto.Clone(pr).(*pb.ProcessResult)
 	if result != nil {
 		for i := range result.Errors {
-			result.Errors[i].Error = nil
+			result.Errors[i].Msg = ""
```
Comment (csuzhangxc) [inline dm/worker/status.go:206]: now, our `Msg` do not including error codes, class, etc.

update this line will change the response from 

```
                    "errors": [
                        {
                            "Type": "UnknownError",
                            "msg": "TCPReader get relay event with error: ERROR 1236 (HY000): Could not find first log file name in binary log index file",
                            "error": null
                        }
                    ],
```

to

```
                        "errors": [
                            {
                                "Type": "UnknownError",
                                "msg": "",
                                "error": {
                                    "ErrCode": 10006,
                                    "ErrClass": 1,
                                    "ErrScope": 2,
                                    "ErrLevel": 3,
                                    "Message": "run table schema failed - dbfile ./dumped_data.task_single/db_single.tbl-schema.sql: execute statement failed: CREATE TABLE `tbl` (`c1` int(11) NOT NULL,`ct` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创 建时间',PRIMARY KEY (`c1`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;: Error 1067: Invalid default value for 'ct'",
                                    "RawCause": "Error 1067: Invalid default value for 'ct'"
                                }
                            }
                        ],
```

File: dm/worker/task_checker.go [hunk 2]
```diff
@@ -263,25 +263,21 @@ func isResumableError(err *pb.ProcessError) bool {
 		return true
 	}
 
-	switch err.Type {
-	case pb.ErrorType_ExecSQL:
```
Comment (csuzhangxc) [inline dm/worker/task_checker.go:267]: We should remove this `ProcessError.Type` later because we have better `code`, `class`, etc. cc @GMHDBJD

File: dm/worker/task_checker_test.go [hunk 3]
```diff
@@ -292,32 +292,31 @@ func (s *testTaskCheckerSuite) TestCheckTaskIndependent(c *check.C) {
...
 		// others
-		{pb.ErrorType_UnknownError, nil, true},
-		{pb.ErrorType_UnknownError, errors.New("unknown error"), true},
+		{nil, true},
+		{errors.New("unknown error"), true},
 	}
 
 	for _, tc := range testCases {
-		err := unit.NewProcessError(tc.errorType, tc.err)
+		err := unit.NewProcessError(pb.ErrorType_UnknownError, tc.err)
```
Comment (csuzhangxc) [inline dm/worker/task_checker_test.go:319]: this `pb.ErrorType_UnknownError` should be removed later.

File: dm/worker/task_checker.go (hunk 2 above)
Comment (GMHDBJD) [reply dm/worker/task_checker.go:267]: Will do it in #746 later

File: dm/worker/status.go [hunk 4]
```diff
@@ -194,16 +194,18 @@ func (w *Worker) Error(stName string) []*pb.SubTaskError {
...
 func statusProcessResult(pr *pb.ProcessResult) *pb.ProcessResult {
 	if pr == nil {
 		return nil
 	}
 	result := proto.Clone(pr).(*pb.ProcessResult)
 	if result != nil {
 		for i := range result.Errors {
-			result.Errors[i].Error = nil
+			if result.Errors[i].Error != nil {
+				result.Errors[i].Msg = ""
```
Comment (csuzhangxc) [inline dm/worker/status.go:207]: now, our `Msg` do not including error codes, class, etc.

update this line will change the response from 

```
                    "errors": [
                        {
                            "Type": "UnknownError",
                            "msg": "TCPReader get relay event with error: ERROR 1236 (HY000): Could not find first log file name in binary log index file",
                            "error": null
                        }
                    ],
```

to

```
                        "errors": [
                            {
                                "Type": "UnknownError",
                                "msg": "",
                                "error": {
                                    "ErrCode": 10006,
                                    "ErrClass": 1,
                                    "ErrScope": 2,
                                    "ErrLevel": 3,
                                    "Message": "run table schema failed - dbfile ./dumped_data.task_single/db_single.tbl-schema.sql: execute statement failed: CREATE TABLE `tbl` (`c1` int(11) NOT NULL,`ct` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '创 建时间',PRIMARY KEY (`c1`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;: Error 1067: Invalid default value for 'ct'",
                                    "RawCause": "Error 1067: Invalid default value for 'ct'"
                                }
                            }
                        ],
```

**Comment by csuzhangxc** [comment]
@WangXiangUSTC @GMHDBJD PTAL
