### PR TITLE
checkpoint: flush global checkpoint when first time flush checkpoint

### LINKED ISSUE #757: restart task fail to get binlog.
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
ticase-94 https://github.com/pingcap/dm/blob/1e00076be2d2f3fc9086698d6a8e4d18f7a6036b/tests/shardddl/run.sh#L1266
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/dm_ghpr_test/detail/dm_ghpr_test/5401/pipeline/68
2. What did you expect to see?
dm work well when restart
3. What did you see instead?
```
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:23.930 +08:00] [INFO] [subtask.go:210] ["start to run"] [subtask=test] [unit=Sync]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:23.933 +08:00] [INFO] [checkpoint.go:792] ["parsing metadata from file"] [task=test] [unit="binlog replication"] [component="remote checkpoint"] [file=dumped_data.test/metadata]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:23.933 +08:00] [INFO] [checkpoint.go:755] ["loaded checkpoints from meta"] [task=test] [unit="binlog replication"] [component="remote checkpoint"] ["global checkpoint"="position: (test-a21cb7e2-4f56-4a9d-a7b5-8a3d319aedeb-c5ns7-rqjq1-bin.000001, 8476), gtid-set: b7bd3425-b471-11ea-8c48-ea984c9134a6:1-40(flushed position: (test-a21cb7e2-4f56-4a9d-a7b5-8a3d319aedeb-c5ns7-rqjq1-bin.000001, 8476), gtid-set: b7bd3425-b471-11ea-8c48-ea984c9134a6:1-40)"]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:23.934 +08:00] [INFO] [syncer.go:1062] ["replicate binlog from checkpoint"] [task=test] [unit="binlog replication"] [checkpoint="position: (test-a21cb7e2-4f56-4a9d-a7b5-8a3d319aedeb-c5ns7-rqjq1-bin.000001, 8476), gtid-set: b7bd3425-b471-11ea-8c48-ea984c9134a6:1-40"]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:23.939 +08:00] [INFO] [streamer_controller.go:66] ["last slave connection"] [task=test] [unit="binlog replication"] ["connection ID"=589]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:23.942 +08:00] [INFO] [mode.go:99] ["change count"] [task=test] [unit="binlog replication"] ["previous count"=0] ["new count"=0]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:23.942 +08:00] [INFO] [mode.go:99] ["change count"] [task=test] [unit="binlog replication"] ["previous count"=0] ["new count"=1]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:23.993 +08:00] [INFO] [server.go:493] [request=QueryStatus] [payload="name:\"test\" "]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.135 +08:00] [INFO] [syncer.go:839] ["flush checkpoints except for these tables"] [task=test] [unit="binlog replication"] [tables="[]"]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.135 +08:00] [INFO] [syncer.go:842] ["prepare flush sqls"] [task=test] [unit="binlog replication"] ["shard meta sqls"="[\"DELETE FROM `dm_meta`.`test_syncer_sharding_meta` where source_id=? and target_table_id=?\"]"] ["shard meta arguments"="[[\"mysql-replica-01\",\"`shardddl`.`tb`\"]]"]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.141 +08:00] [INFO] [syncer.go:851] ["flushed checkpoint"] [task=test] [unit="binlog replication"] [checkpoint="position: (test-a21cb7e2-4f56-4a9d-a7b5-8a3d319aedeb-c5ns7-rqjq1-bin.000001, 8476), gtid-set: b7bd3425-b471-11ea-8c48-ea984c9134a6:1-40(flushed position: (test-a21cb7e2-4f56-4a9d-a7b5-8a3d319aedeb-c5ns7-rqjq1-bin.000001, 8476), gtid-set: b7bd3425-b471-11ea-8c48-ea984c9134a6:1-40)"]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.198 +08:00] [INFO] [worker.go:275] ["stop sub task"] [component="worker controller"] [task=test]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.198 +08:00] [INFO] [subtask.go:424] [closing] [subtask=test]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.198 +08:00] [INFO] [subtask.go:345] ["closing unit process"] [subtask=test] [unit=Sync]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.198 +08:00] [INFO] [syncer.go:2126] ["print status routine exits"] [task=test] [unit="binlog replication"] [error="context canceled"]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.198 +08:00] [INFO] [mode.go:99] ["change count"] [task=test] [unit="binlog replication"] ["previous count"=1] ["new count"=0]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.199 +08:00] [INFO] [server.go:493] [request=QueryStatus] [payload="name:\"test\" "]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.225 +08:00] [INFO] [syncer.go:1215] ["binlog replication main routine quit(context canceled)!"] [task=test] [unit="binlog replication"] ["last location"="position: (test-a21cb7e2-4f56-4a9d-a7b5-8a3d319aedeb-c5ns7-rqjq1-bin.000001, 8731), gtid-set: b7bd3425-b471-11ea-8c48-ea984c9134a6:1-40"]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.235 +08:00] [WARN] [syncer.go:824] ["error detected when executing SQL job, skip flush checkpoint"] [task=test] [unit="binlog replication"] [checkpoint="position: (test-a21cb7e2-4f56-4a9d-a7b5-8a3d319aedeb-c5ns7-rqjq1-bin.000001, 8731), gtid-set: b7bd3425-b471-11ea-8c48-ea984c9134a6:1-40(flushed position: (test-a21cb7e2-4f56-4a9d-a7b5-8a3d319aedeb-c5ns7-rqjq1-bin.000001, 8476), gtid-set: b7bd3425-b471-11ea-8c48-ea984c9134a6:1-40)"]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.238 +08:00] [INFO] [checkpoint.go:556] ["rollback checkpoint"] [task=test] [unit="binlog replication"] [component="remote checkpoint"] [schema=shardddl1] [table=tb2] [from="position: (test-a21cb7e2-4f56-4a9d-a7b5-8a3d319aedeb-c5ns7-rqjq1-bin.000001, 8955), gtid-set: b7bd3425-b471-11ea-8c48-ea984c9134a6:1-40"] [to="position: (, 4), gtid-set: "]
[2020-06-22T10:25:32.703Z] [2020/06/22 18:25:24.529 +08:00] [INFO] [server.go:493] [request=QueryStatus] [payload="name:\"test\" "]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:24.539 +08:00] [INFO] [worker.go:236] ["started sub task"] [component="worker controller"] [config="{\"is-sharding\":true,\"shard-mode\":\"pessimistic\",\"online-ddl-scheme\":\"\",\"case-sensitive\":false,\"name\":\"test\",\"mode\":\"all\",\"ignore-checking-items\":null,\"source-id\":\"mysql-replica-01\",\"server-id\":429595830,\"flavor\":\"mysql\",\"meta-schema\":\"dm_meta\",\"heartbeat-update-interval\":1,\"heartbeat-report-interval\":1,\"enable-heartbeat\":false,\"meta\":null,\"Timezone\":\"Asia/Shanghai\",\"relay-dir\":\"/tmp/dm_test/shardddl/worker1/relay_log\",\"use-relay\":false,\"from\":{\"host\":\"127.0.0.1\",\"port\":3306,\"user\":\"root\",\"max-allowed-packet\":67108864,\"session\":null},\"to\":{\"host\":\"127.0.0.1\",\"port\":4000,\"user\":\"test\",\"max-allowed-packet\":67108864,\"session\":null},\"route-rules\":[{\"schema-pattern\":\"shardddl*\",\"table-pattern\":\"tb*\",\"target-schema\":\"shardddl\",\"target-table\":\"tb\"},{\"schema-pattern\":\"shardddl*\",\"table-pattern\":\"\",\"target-schema\":\"shardddl\",\"target-table\":\"\"}],\"filter-rules\":[],\"mapping-rule\":[],\"black-white-list\":{\"do-tables\":null,\"do-dbs\":[\"shardddl1\",\"shardddl2\"],\"ignore-tables\":null,\"ignore-dbs\":null},\"mydumper-path\":\"./bin/mydumper\",\"threads\":4,\"chunk-filesize\":\"64\",\"statement-size\":0,\"rows\":0,\"where\":\"\",\"skip-tz-utc\":true,\"extra-args\":\"\",\"pool-size\":16,\"dir\":\"./dumped_data.test\",\"meta-file\":\"\",\"worker-count\":16,\"batch\":100,\"queue-size\":1024,\"checkpoint-flush-interval\":30,\"max-retry\":0,\"auto-fix-gtid\":false,\"enable-gtid\":false,\"disable-detect\":false,\"safe-mode\":false,\"enable-ansi-quotes\":false,\"log-level\":\"\",\"log-file\":\"\",\"log-rotate\":\"\",\"pprof-addr\":\"\",\"status-addr\":\"\",\"config-file\":\"\"}"]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:24.540 +08:00] [INFO] [syncer.go:2548] ["use timezone"] [task=test] [unit="binlog replication"] [location=Asia/Shanghai]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:25.533 +08:00] [INFO] [server.go:493] [request=QueryStatus] [payload="name:\"test\" "]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.668 +08:00] [INFO] [dumpling.go:242] ["create dumpling"] [task=test] [unit=dump] [config="{\"Databases\":null,\"Host\":\"127.0.0.1\",\"User\":\"root\",\"Port\":3306,\"Password\":\"123456\",\"Threads\":4,\"LogLevel\":\"\",\"LogFile\":\"\",\"LogFormat\":\"\",\"Logger\":{},\"FileSize\":67108864,\"StatementSize\":0,\"OutputDirPath\":\"./dumped_data.test\",\"ServerInfo\":{\"ServerType\":0,\"ServerVersion\":null},\"SortByPk\":true,\"Tables\":null,\"StatusAddr\":\"\",\"Snapshot\":\"\",\"Consistency\":\"auto\",\"NoViews\":true,\"NoHeader\":false,\"NoSchemas\":false,\"NoData\":false,\"CsvNullValue\":\"\\\\N\",\"Sql\":\"\",\"TableFilter\":{},\"Rows\":0,\"Where\":\"\",\"FileType\":\"SQL\",\"EscapeBackslash\":true}"]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.669 +08:00] [WARN] [dumpling.go:244] ["meeting some unsupported arguments"] [task=test] [unit=dump] [argument="[--skip-tz-utc]"]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.726 +08:00] [INFO] [sharding_group.go:710] ["execute sql"] [task=test] [unit="binlog replication"] [component="shard group keeper"] [statement="CREATE SCHEMA IF NOT EXISTS `dm_meta`"]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.728 +08:00] [INFO] [sharding_group.go:728] ["execute sql"] [task=test] [unit="binlog replication"] [component="shard group keeper"] [statement="CREATE TABLE IF NOT EXISTS `dm_meta`.`test_syncer_sharding_meta` (\n\t\tsource_id VARCHAR(32) NOT NULL COMMENT 'replica source id, defined in task.yaml',\n\t\ttarget_table_id VARCHAR(144) NOT NULL,\n\t\tsource_table_id  VARCHAR(144) NOT NULL,\n\t\tactive_index INT,\n\t\tis_global BOOLEAN,\n\t\tdata JSON,\n\t\tcreate_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\tupdate_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n\t\tUNIQUE KEY uk_source_id_table_id_source (source_id, target_table_id, source_table_id)\n\t)"]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.731 +08:00] [INFO] [common.go:109] ["no tables need to sync"] [schema=shardddl2]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.736 +08:00] [INFO] [checkpoint.go:605] ["create checkpoint schema"] [task=test] [unit="binlog replication"] [component="remote checkpoint"] [statement="CREATE SCHEMA IF NOT EXISTS `dm_meta`"]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.738 +08:00] [INFO] [checkpoint.go:626] ["create checkpoint table"] [task=test] [unit="binlog replication"] [component="remote checkpoint"] [statements="[\"CREATE TABLE IF NOT EXISTS `dm_meta`.`test_syncer_checkpoint` (\\n\\t\\t\\tid VARCHAR(32) NOT NULL,\\n\\t\\t\\tcp_schema VARCHAR(128) NOT NULL,\\n\\t\\t\\tcp_table VARCHAR(128) NOT NULL,\\n\\t\\t\\tbinlog_name VARCHAR(128),\\n\\t\\t\\tbinlog_pos INT UNSIGNED,\\n\\t\\t\\tbinlog_gtid VARCHAR(256),\\n\\t\\t\\ttable_info JSON NOT NULL,\\n\\t\\t\\tis_global BOOLEAN,\\n\\t\\t\\tcreate_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\\n\\t\\t\\tupdate_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\\n\\t\\t\\tUNIQUE KEY uk_id_schema_table (id, cp_schema, cp_table)\\n\\t\\t)\"]"]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.874 +08:00] [INFO] [subtask.go:166] ["continue unit"] [subtask=test] [unit=Sync]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.875 +08:00] [INFO] [loader.go:636] ["stop importing data process"] [task=test] [unit=load]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.877 +08:00] [INFO] [subtask.go:210] ["start to run"] [subtask=test] [unit=Sync]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.877 +08:00] [INFO] [worker.go:431] ["load subtask"] [sourceID=mysql-replica-01] [task=test]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.881 +08:00] [INFO] [syncer.go:1062] ["replicate binlog from checkpoint"] [task=test] [unit="binlog replication"] [checkpoint="position: (, 4), gtid-set: "]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.887 +08:00] [INFO] [streamer_controller.go:66] ["last slave connection"] [task=test] [unit="binlog replication"] ["connection ID"=604]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.889 +08:00] [INFO] [mode.go:99] ["change count"] [task=test] [unit="binlog replication"] ["previous count"=0] ["new count"=0]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.889 +08:00] [INFO] [mode.go:99] ["change count"] [task=test] [unit="binlog replication"] ["previous count"=0] ["new count"=1]
[2020-06-22T10:25:32.704Z] [2020/06/22 18:25:26.890 +08:00] [ERROR] [syncer.go:1268] ["fail to get index number of binlog file"] [task=test] [unit="binlog replication"] [error="[code=22002:class=binlog-op:scope=internal:level=high] filename : invalid binlog filename"]
```

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
close #757

### What is changed and how it works?
flush global checkpoint when first flush checkpoint

### Check List 

Tests 

 - Unit test

### CODE REVIEW

File: syncer/syncer_test.go [hunk 1]
```diff
@@ -1061,6 +1061,17 @@ func (s *testSyncerSuite) TestCasuality(c *C) {
...
+	c.Assert(err, IsNil)
+	dbConn, err := db.Conn(context.Background())
+	c.Assert(err, IsNil)
+
+	syncer.checkpoint.(*RemoteCheckPoint).dbConn = &DBConn{cfg: s.cfg, baseConn: conn.NewBaseConn(dbConn, &retry.FiniteRetryStrategy{})}
+	syncer.checkpoint.(*RemoteCheckPoint).prepare(tcontext.Background())
+
+	mock.ExpectBegin()
+	mock.ExpectExec(".*INSERT INTO .* VALUES.* ON DUPLICATE KEY UPDATE.*").WillReturnResult(sqlmock.NewResult(0, 1))
+	mock.ExpectCommit()
```
Comment (csuzhangxc) [inline syncer/syncer_test.go:1074]: Is `mock.ExpectationsWereMet` needed?

**Comment by GMHDBJD** [comment]
@WangXiangUSTC @csuzhangxc PTAL again ~

File: syncer/syncer_test.go (hunk 1 above)
Comment (GMHDBJD) [reply syncer/syncer_test.go:1074]: add in c96b6c1
