### PR TITLE
syncer: do not ignore fake rotate event to the next file

### LINKED ISSUE #1038: syncer doesn't rotate to the next binlog file when no RotateEvent in the current binlog file
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   stop and start the upstream MySQL server when replicating incremental data.

2. What did you expect to see?

    the task resumed automatically after the upstream MySQL restarted.

3. What did you see instead?

    ```
    [2020/09/15 15:17:56.076 +08:00] [ERROR] [subtask.go:295] ["unit process error"] [subtask=task_single] [unit=Sync] ["error information"="{\"ErrCode\":36001,\"ErrClass\":\"sync-unit\",\"ErrScope\":\"internal\",\"ErrLevel\":\"high\",\"Message\":\"panic error: table checkpoint position: (mysql-bin.000002, 568), gtid-set: 074be7f4-f0f1-11ea-95bd-0242ac120002:1-153 less than global checkpoint position: (mysql-bin.000002, 25660968), gtid-set: 074be7f4-f0f1-11ea-95bd-0242ac120002:1-153(flushed position: (mysql-bin.000002, 25660968), gtid-set: 074be7f4-f0f1-11ea-95bd-0242ac120002:1-153)\"}"]
    ```

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.0-rc.2
        ```
[dm-worker-checkpoint.log](https://github.com/pingcap/dm/files/5223473/dm-worker-checkpoint.log)

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

fix #1038

### What is changed and how it works?

only skip the fake rotate event if it's not to the next binlog file.

NOTE:
- MySQL server will write a RotateEvent before rotate to the next binlog file normally.
- MySQL server will send a _fake_ RotateEvent to the slave before sending other real binlog events.
- MySQL server will write a StopEvent at the end of a binlog file when stoping itself but without RotateEvent
- MySQL server will write from a new binlog file after started itself

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
     - trigger the error reported in #1038 with an older version of DM
     - replace DM-worker with a newer version in this PR
     - observe the task resumed

Code changes

Side effects

 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch
 - Need to be included in the release note

### CODE REVIEW

File: syncer/syncer.go [hunk 1]
```diff
@@ -1497,9 +1497,10 @@ type eventContext struct {
 // TODO: Further split into smaller functions and group common arguments into
 // a context struct.
 func (s *Syncer) handleRotateEvent(ev *replication.RotateEvent, ec eventContext) error {
-	if ec.header.Timestamp == 0 || ec.header.LogPos == 0 {
-		// it is fake rotate event, ignore it
-		return nil
+	if ec.header.Timestamp == 0 || ec.header.LogPos == 0 { // fake rotate event
+		if string(ev.NextLogName) <= ec.lastLocation.Position.Name {
+			return nil // not rotate to the next binlgo file, ignore it
```
Comment (lance6716) [inline syncer/syncer.go:1502]:
```suggestion
			return nil // not rotate to the next binlog file, ignore it
```

**Comment by lance6716** [comment]
LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM
