### PR TITLE
election: don't forwarding when startLeaderComponent

### LINKED ISSUE #1088: do not forward requests once a DM-master itself become the leader
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

    ```
    [2020/09/23 15:25:59.801 +08:00] [INFO] [election.go:55] ["current member become the leader"] ["current member"=master2]
    [2020/09/23 15:25:59.801 +08:00] [INFO] [scheduler.go:163] ["the scheduler is starting"] [component=scheduler]
    ...
    [2020/09/23 15:26:00.264 +08:00] [INFO] [server.go:2203] ["will forward after a short interval"] [from=master2] [to=master3] [request=ListMember]
    ...
    [2020/09/23 15:26:07.019 +08:00] [INFO] [scheduler.go:205] ["the scheduler has started"] [component=scheduler]
    [2020/09/23 15:26:07.020 +08:00] [INFO] [pessimist.go:69] ["the shard DDL pessimist is starting"] [component="shard DDL pessimist"]
    ```

4. Versions of the cluster

    - DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):

        ```
        v2.0.0-rc.2 at least until https://github.com/pingcap/dm/commit/55fcd6db4446ef81e9081d932355b1e99a487604
        ```

[6889-77.log](https://github.com/pingcap/dm/files/5273347/6889-77.log)

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #1088 

### What is changed and how it works?
lock more code

### Check List 

Tests 

 - Pass original test

Code changes

Side effects

 - Possible performance regression

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by lance6716** [comment]
caused a problem

```
[2020/09/29 18:49:20.902 +08:00] [INFO] [grpclog.go:45] ["pickfirstBalancer: HandleSubConnStateChange: 0xc000d2d630, {CONNECTING <nil>}"] [component="embed etcd"]
[2020/09/29 18:49:20.902 +08:00] [INFO] [grpclog.go:45] ["transport: loopyWriter.run returning. connection error: desc = \"transport is closing\""] [component="embed etcd"]
[2020/09/29 18:49:20.903 +08:00] [INFO] [grpclog.go:45] ["pickfirstBalancer: HandleSubConnStateChange: 0xc000d2d630, {READY <nil>}"] [component="embed etcd"]
[2020/09/29 18:49:20.903 +08:00] [INFO] [grpclog.go:45] ["pickfirstBalancer: HandleSubConnStateChange: 0xc000d2d750, {CONNECTING <nil>}"] [component="embed etcd"]
[2020/09/29 18:49:20.903 +08:00] [INFO] [grpclog.go:45] ["transport: loopyWriter.run returning. connection error: desc = \"transport is closing\""] [component="embed etcd"]
[2020/09/29 18:49:20.904 +08:00] [INFO] [grpclog.go:45] ["pickfirstBalancer: HandleSubConnStateChange: 0xc000d2d750, {READY <nil>}"] [component="embed etcd"]
[2020/09/29 18:49:21.772 +08:00] [INFO] [grpclog.go:45] ["transport: loopyWriter.run returning. connection error: desc = \"transport is closing\""] [component="embed etcd"]
```

**Comment by lance6716** [comment]
log in #1088

```
[2020/09/23 15:25:59.801 +08:00] [INFO] [election.go:55] ["current member become the leader"] ["current member"=master2]
...
[2020/09/23 15:26:00.263 +08:00] [INFO] [server.go:2188] [payload="leader:true "] [request=ListMember]
[2020/09/23 15:26:00.264 +08:00] [INFO] [server.go:2203] ["will forward after a short interval"] [from=master2] [to=master3] [request=ListMember]
...
[2020/09/23 15:26:02.518 +08:00] [INFO] [server.go:2188] [payload="leader:true "] [request=ListMember]
[2020/09/23 15:26:02.518 +08:00] [INFO] [server.go:2203] ["will forward after a short interval"] [from=master2] [to=master3] [request=ListMember]
...
[2020/09/23 15:26:04.780 +08:00] [INFO] [server.go:2188] [payload="leader:true "] [request=ListMember]
[2020/09/23 15:26:04.780 +08:00] [INFO] [server.go:2203] ["will forward after a short interval"] [from=master2] [to=master3] [request=ListMember]
...
[2020/09/23 15:26:07.092 +08:00] [INFO] [optimist.go:87] ["the shard DDL optimist has started"] [component="shard DDL optimist"]
[2020/09/23 15:26:07.244 +08:00] [INFO] [server.go:2188] [payload="leader:true "] [request=ListMember]
```

this PR now will return to dm-ctl en error that failed to forward after waiting 1s. I'm afraid that's too short because in above log  master used 7s to finish `startLeaderComponent`. should we improve waiting time?

and in fact, before this PR, request will forward back and forth and finally success with longer response time. after this PR it will fail quickly. Is this expected?

File: pkg/atomic2/atomic.go [hunk 1]
```diff
@@ -36,3 +36,22 @@ func (e *AtomicError) Get() error {
 func (e *AtomicError) Set(err error) {
 	atomic.StorePointer(&e.p, unsafe.Pointer(&err))
 }
+
+// AtomicString implements atomic string method
+type AtomicString struct {
+	p unsafe.Pointer
+}
+
+// Get returns error
```
Comment (csuzhangxc) [inline pkg/atomic2/atomic.go:45]: please fix this comment and ditto for L54.

File: dm/master/election.go [hunk 2]
```diff
@@ -126,11 +128,24 @@ func (s *Server) closeLeaderClient() {
 }
 
 func (s *Server) isLeaderAndNeedForward() (isLeader bool, needForward bool) {
+	retry := 10
+	wait := 100 * time.Millisecond
+	for ; retry > 0; retry-- {
+		if s.leader.Get() == oneselfStartingLeader {
+			time.Sleep(wait)
```
Comment (csuzhangxc) [inline dm/master/election.go:135]: if we want to wait more time, `time.After` (or tick) combine with `ctx` is always better than `time.Sleep` because we may need to support cancel this waiting. (IMO, `time.Sleep` is not a good choice in production code)

**Comment by csuzhangxc** [comment]
> this PR now will return to dm-ctl an error that failed to forward after waiting 1s. I'm afraid that's too short because in above log master used 7s to finish startLeaderComponent. should we improve waiting time?

I think no need to waiting more time, just give a clear error is enough.

> and in fact, before this PR, request will forward back and forth and finally success with longer response time. after this PR it will fail quickly. Is this expected?

I think this is expected.

File: dm/master/election.go [hunk 3]
```diff
@@ -127,20 +127,26 @@ func (s *Server) closeLeaderClient() {
...
+func (s *Server) isLeaderAndNeedForward(ctx context.Context) (isLeader bool, needForward bool) {
+	// maybe in `startLeaderComponent`, will wait for a short time
+	if s.leader.Get() == oneselfStartingLeader {
+		retry := 10
+		ticker := time.NewTicker(100 * time.Millisecond)
+		defer ticker.Stop()
+
+		for s.leader.Get() == oneselfStartingLeader {
+			if retry == 0 {
+				return false, false
```
Comment (csuzhangxc) [inline dm/master/election.go:139]: How about adding a log for this case?

**Review by csuzhangxc — COMMENTED** [review]
rest LGTM

File: dm/master/election.go (hunk 3 above)
Comment (lance6716) [reply dm/master/election.go:140]: done in https://github.com/pingcap/dm/pull/1118/commits/020197916448fd1cc2d0a71df6d18b63995f63c2

**Review by csuzhangxc — COMMENTED** [review]
LGTM

**Comment by lance6716** [comment]
PTAL if have spare time @WangXiangUSTC

**Review by WangXiangUSTC — APPROVED** [review]
LGTM
